# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-03 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(choices=[(b'EDT', b'EDT'), (b'justification absence', b'Justification Absence'), (b'demande derogation', b'Derogation'), (b'demande equivalence', b'Demande Equivalence'), (b'liste etudiants ', b'Liste Etudiants'), (b'theme pfe ', b'Theme Pfe '), (b'copie examen', b'Copies examens '), (b'feuille de presence', b'Feuille Presence')], default=b'choisir ', max_length=1502)),
                ('dateArrive', models.DateField(default=django.utils.timezone.now)),
                ('expediteur', models.CharField(choices=[(b'etudiant', b'Etudiant'), (b'enseignant', b'Enseignant'), (b'responsable filiere', b'Responsable Filiere'), (b'chef departement ', b'Chef Departement '), (b'adjoint pedagogie ', b'Adjoint Pedagogie'), (b'responsable domaine ', b'Responsable Domaine')], max_length=100)),
                ('nom', models.CharField(blank=True, default=b'', max_length=100)),
                ('surnom', models.CharField(blank=True, max_length=100)),
                ('parcours', models.CharField(choices=[(b'l1', b'L1'), (b'l2', b'L2'), (b'l3', b'L3'), (b'm1', b'M1'), (b'm2', b'M2'), (b'd1', b'D1'), (b'd2', b'D2'), (b'd3', b'D3'), (b'd4', b'D4'), (b'd5', b'D5'), (b'tous', b'Tous')], default=b'l1', max_length=10)),
                ('destinataire', models.CharField(choices=[(b'etudiant', b'Etudiant'), (b'enseignant', b'Enseignant'), (b'responsable filiere', b'Responsable Filiere'), (b'chef departement ', b'Chef Departement '), (b'adjoint pedagogie ', b'Adjoint Pedagogie'), (b'responsable domaine ', b'Responsable Domaine'), (b'responsable reprographie', b'Responsable Reprographie')], max_length=100)),
                ('piece_jointe', models.FileField(blank=True, upload_to=b'')),
                ('affichable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CourrierR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(choices=[(b'Tirage TD ', b'tirage td '), (b'Tirage Examen', b'tirage examen'), (b'Archivage Examen', b'archivage examen '), (b'Emprunter Datashow', b'emprunter datashow'), (b'Recuperer datashow', b'recuperer datashow '), (b'Impression', b'impression')], default=b'choisir', max_length=1502)),
                ('dateArrive', models.DateField(default=django.utils.timezone.now)),
                ('expediteur', models.CharField(choices=[(b'etudiant', b'Etudiant'), (b'enseignant', b'Enseignant'), (b'responsable filiere', b'Responsable Filiere'), (b'chef departement ', b'Chef Departement '), (b'adjoint pedagogie ', b'Adjoint Pedagogie'), (b'responsable domaine ', b'Responsable Domaine')], max_length=100)),
                ('nom', models.CharField(blank=True, default=b'', max_length=100)),
                ('surnom', models.CharField(blank=True, max_length=100)),
                ('parcours', models.CharField(choices=[(b'l1', b'L1'), (b'l2', b'L2'), (b'l3', b'L3'), (b'm1', b'M1'), (b'm2', b'M2'), (b'd1', b'D1'), (b'd2', b'D2'), (b'd3', b'D3'), (b'd4', b'D4'), (b'd5', b'D5'), (b'tous', b'Tous')], default=b'l1', max_length=10)),
                ('Nbr', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='justificatif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateAbsence', models.DateField(default=django.utils.timezone.now)),
                ('dateJustification', models.DateField(default=django.utils.timezone.now)),
                ('valide', models.BooleanField(default=True)),
                ('dateArrive', models.DateField(default=django.utils.timezone.now)),
                ('nom', models.CharField(blank=True, default=b'', max_length=100)),
                ('surnom', models.CharField(blank=True, max_length=100)),
                ('parcours', models.CharField(choices=[(b'l1', b'L1'), (b'l2', b'L2'), (b'l3', b'L3'), (b'm1', b'M1'), (b'm2', b'M2'), (b'd1', b'D1'), (b'd2', b'D2'), (b'd3', b'D3'), (b'd4', b'D4'), (b'd5', b'D5'), (b'tous', b'Tous')], default=b'l1', max_length=10)),
            ],
        ),
    ]
