# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-03 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioncourrier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='justificatif',
            name='valide',
            field=models.CharField(choices=[(b'Valide', b'valide'), (b'Nonvalide', b'non-valide')], default=b'nonv-alide', max_length=10),
        ),
    ]
