# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-03 23:42
from __future__ import unicode_literals

import computed_property.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestioncourrier', '0002_auto_20180603_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='justificatif',
            name='valide',
            field=computed_property.fields.ComputedCharField(compute_from=b'fun', editable=False, max_length=10),
        ),
    ]
